import { Landmark, ShieldAlert } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { formatDateTime, formatMoney, formatPercent } from "@/lib/format";
import { trpc } from "@/lib/trpc";

export default function PositionsPage() {
  const positions = trpc.telemetry.positions.useQuery(undefined, { refetchInterval: 3_000, retry: 1 });
  return <div className="page-enter"><PageHeader title="Posições em aberto" description="Exposição atual marcada a mercado; informações renovadas automaticamente a cada 3 segundos." action={<div className="status-chip status-healthy"><Landmark className="h-3.5 w-3.5" />POLLING 3S</div>} />{positions.error && <p className="mb-5 text-sm text-rose-300">{positions.error.message}</p>}<section className="cyber-surface overflow-hidden"><div className="overflow-x-auto"><table className="data-table min-w-[850px]"><thead><tr><th>Par</th><th>Entrada</th><th>Quantidade</th><th>Preço atual</th><th>P&L %</th><th>P&L USDT</th><th>Aberta em</th></tr></thead><tbody>{positions.data?.positions.map(position => <tr key={position.symbol}><td className="font-semibold text-foreground">{position.symbol}</td><td>{formatMoney(position.entry_price, 6)}</td><td>{formatMoney(position.quantity, 6)}</td><td>{position.current_price === null ? "aguardando" : formatMoney(position.current_price, 6)}</td><td className={(position.pnl_pct ?? 0) >= 0 ? "text-[#00ff88]" : "text-rose-300"}>{position.pnl_pct === null ? "—" : formatPercent(position.pnl_pct)}</td><td className={(position.pnl_usdt ?? 0) >= 0 ? "text-[#00ff88]" : "text-rose-300"}>{position.pnl_usdt === null ? "—" : `${formatMoney(position.pnl_usdt)} USDT`}</td><td>{formatDateTime(position.opened_at)}</td></tr>) ?? null}{positions.isLoading && <tr><td colSpan={7} className="py-16 text-center text-sm text-muted-foreground">Carregando posições…</td></tr>}{!positions.isLoading && !positions.data?.positions.length && <tr><td colSpan={7} className="py-16 text-center"><ShieldAlert className="mx-auto mb-3 h-5 w-5 text-muted-foreground" /><p className="text-sm text-muted-foreground">Nenhuma posição está aberta no momento.</p></td></tr>}</tbody></table></div></section></div>;
}
