export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  botApiBaseUrl: process.env.BOT_API_BASE_URL ?? "",
  botLogsUrl: process.env.BOT_LOGS_URL ?? "",
  dashboardApiKey: process.env.DASHBOARD_API_KEY ?? "",
  easypanelBaseUrl: process.env.EASYPANEL_BASE_URL ?? "",
  easypanelApiKey: process.env.EASYPANEL_API_KEY ?? "",
};
